### ISSUE TITLE
for android studio help

### ISSUE THREAD

**Issue by VAS-QZ** [joaopedronardari/OpenCV-AndroidSamples#2]
I meet a problem about that for when I set the sample in my android studio and make a apk.
the android studio will meet a error.It tell me the function OpenCVLoader.initAsync() meet a error.
I don`t know why, could you help me?

**Comment by joaopedronardari** [comment]
Hello @VAS-QZ! I will try to run again in my new Android Studio to see what happens, ok?

**Comment by Johnxiaowei** [comment]
Can you tell me how to solve this problem it , 
the problem described below.
Error:(19, 67) error: invalid user-defined conversion from 'int' to 'const string& {aka const std::basic_string<char>&}' [-fpermissive]

**Comment by Johnxiaowei** [comment]
I put the code into your project AS, and then modify the path opencv sdk , but the wrong item , it could not find the error <jni.h> header file and so on , can you help me solve it ?

**Comment by 5amron** [comment]
should I setup NDK on my android studio to run your project @joaopedronardari ? or there is an other way.

**Comment by joaopedronardari** [comment]
Yes, I have to download NDK in Android SDK Manager

**Comment by joaopedronardari** [comment]
Yes, you have to download Android NDK in Android SDK Manager :)

**Comment by 5amron** [comment]
thanks!
